# Generated by Django 3.0.5 on 2021-01-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField()),
                ('worker_id', models.CharField()),
                ('permissions', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField()),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('work_type', models.CharField()),
                ('work_norm', models.CharField()),
                ('phone_number', models.CharField()),
            ],
        ),
    ]
