from enum import Enum


class Permissions(Enum):
    CONTACTS_READ = "CONTACTS_READ"
    ALL_USERS_READ = "ALL_USERS_READ"
    USER_READ = "USER_READ"
    WORK_SHIFTS_READ = "WORK_SHIFTS_READ"
    USER_CONTACTS_READ = "USER_CONTACTS_READ"
    USER_SHIFTS_READ = "USER_SHIFTS_READ"
    USER_ADD = "USER_ADD"
    USER_MOD = "USER_MOD"
    USER_REMOVE = "USER_REMOVE"